/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.expenses.jsonc --include-runtime=false --env-interface=ExpenseEnv expense-configuration.d.ts` (hash: 07467e2e97697853007424c0d433e571)
interface __BaseEnv_ExpenseEnv {
	DEEPSEEK_MODEL: "deepseek-v4-flash";
	CHAT_DEFAULT_MODEL: "deepseek-v4-flash";
	EMBEDDING_DIMENSIONS: "1536";
	CF_WORKER_TRIGGER_SECRET: string;
	PLANE_INTERNAL_API_SECRET: string;
	OPENAI_API_KEY: string;
	GOOGLE_GENERATIVE_AI_API_KEY: string;
	DEEPSEEK_API_KEY: string;
	TEXT_EXTRACTOR_API_URL: string;
	PLANE_INTERNAL_API_URL: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	AI_PROVIDER: string;
	AWS_REGION: string;
	GEMINI_MODEL_FALLBACK_LIST: string;
	DEEPSEEK_MODEL_LIST: string;
	OPENAI_EMBEDDING_MODEL: string;
	TEXT_EXTRACTION_MODE: string;
	ASSISTANT_AI_PROVIDER: string;
	EXPENSE_PIPELINE: Workflow<Parameters<import("./src/expenses/index").ExpensePipelineWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/expenses/index");
	}
	interface Env extends __BaseEnv_ExpenseEnv {}
}
interface ExpenseEnv extends __BaseEnv_ExpenseEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEEPSEEK_MODEL" | "CHAT_DEFAULT_MODEL" | "EMBEDDING_DIMENSIONS" | "CF_WORKER_TRIGGER_SECRET" | "PLANE_INTERNAL_API_SECRET" | "OPENAI_API_KEY" | "GOOGLE_GENERATIVE_AI_API_KEY" | "DEEPSEEK_API_KEY" | "TEXT_EXTRACTOR_API_URL" | "PLANE_INTERNAL_API_URL" | "AWS_ACCESS_KEY_ID" | "AWS_SECRET_ACCESS_KEY" | "AI_PROVIDER" | "AWS_REGION" | "GEMINI_MODEL_FALLBACK_LIST" | "DEEPSEEK_MODEL_LIST" | "OPENAI_EMBEDDING_MODEL" | "TEXT_EXTRACTION_MODE" | "ASSISTANT_AI_PROVIDER">> {}
}
