/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 59d561078790968b6cdebb4c01312a2f)
interface __BaseEnv_Env {
	ASSISTANT_AI_PROVIDER: "gemini";
	DEEPSEEK_MODEL: "deepseek-v4-flash";
	CHAT_DEFAULT_MODEL: "deepseek-v4-flash";
	EMBEDDING_DIMENSIONS: "1536";
	CF_WORKER_TRIGGER_SECRET: string;
	PLANE_INTERNAL_API_SECRET: string;
	OPENAI_API_KEY: string;
	GOOGLE_GENERATIVE_AI_API_KEY: string;
	DEEPSEEK_API_KEY: string;
	TEXT_EXTRACTOR_API_URL: string;
	PLANE_INTERNAL_API_URL: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	AI_PROVIDER: string;
	AWS_REGION: string;
	GEMINI_MODEL_FALLBACK_LIST: string;
	DEEPSEEK_MODEL_LIST: string;
	OPENAI_EMBEDDING_MODEL: string;
	TEXT_EXTRACTION_MODE: string;
	CONTRACT_PIPELINE: Workflow<Parameters<import("./src/index").ContractPipelineWorkflow['run']>[0]['payload']>;
	CONTRACT_QUERY: Workflow<Parameters<import("./src/index").ContractQueryWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
