# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

from django.urls import path

from plane.app.views import (
    BudgetBonusDetailEndpoint,
    BudgetBonusEndpoint,
    BudgetDetailEndpoint,
    BudgetEndpoint,
    BudgetScenarioDetailEndpoint,
    BudgetScenarioCellOverrideEndpoint,
    BudgetScenarioEmployeeDetailEndpoint,
    BudgetScenarioEmployeeEndpoint,
    BudgetScenarioEndpoint,
    BudgetScenarioExportEndpoint,
    BudgetScenarioSummaryEndpoint,
    BudgetScenarioVariableDetailEndpoint,
    BudgetScenarioVariableEndpoint,
    BudgetSummaryEndpoint,
    ExpenseCategoryDetailEndpoint,
    ExpenseCategoryEndpoint,
    ExpenseDetailEndpoint,
    ExpenseDocumentEndpoint,
    ExpenseDocumentViewEndpoint,
    ExpenseEndpoint,
    FinancialVariableDetailEndpoint,
    FinancialVariableEndpoint,
)

urlpatterns = [
    path(
        "workspaces/<str:slug>/budget-scenarios/",
        BudgetScenarioEndpoint.as_view(),
        name="budget-scenarios",
    ),
    path(
        "workspaces/<str:slug>/budget-scenarios/<uuid:scenario_id>/",
        BudgetScenarioDetailEndpoint.as_view(),
        name="budget-scenario-detail",
    ),
    path(
        "workspaces/<str:slug>/budget-scenarios/<uuid:scenario_id>/summary/",
        BudgetScenarioSummaryEndpoint.as_view(),
        name="budget-scenario-summary",
    ),
    path(
        "workspaces/<str:slug>/budget-scenarios/<uuid:scenario_id>/cells/",
        BudgetScenarioCellOverrideEndpoint.as_view(),
        name="budget-scenario-cells",
    ),
    path(
        "workspaces/<str:slug>/budget-scenarios/<uuid:scenario_id>/export/",
        BudgetScenarioExportEndpoint.as_view(),
        name="budget-scenario-export",
    ),
    path(
        "workspaces/<str:slug>/budget-scenarios/<uuid:scenario_id>/employees/",
        BudgetScenarioEmployeeEndpoint.as_view(),
        name="budget-scenario-employees",
    ),
    path(
        "workspaces/<str:slug>/budget-scenarios/<uuid:scenario_id>/employees/<uuid:assignment_id>/",
        BudgetScenarioEmployeeDetailEndpoint.as_view(),
        name="budget-scenario-employee-detail",
    ),
    path(
        "workspaces/<str:slug>/budget-scenarios/<uuid:scenario_id>/employees/<uuid:assignment_id>/bonuses/",
        BudgetBonusEndpoint.as_view(),
        name="budget-scenario-bonuses",
    ),
    path(
        "workspaces/<str:slug>/budget-scenarios/<uuid:scenario_id>/employees/<uuid:assignment_id>/bonuses/<uuid:bonus_id>/",
        BudgetBonusDetailEndpoint.as_view(),
        name="budget-scenario-bonus-detail",
    ),
    path(
        "workspaces/<str:slug>/budget-scenarios/<uuid:scenario_id>/variables/",
        BudgetScenarioVariableEndpoint.as_view(),
        name="budget-scenario-variables",
    ),
    path(
        "workspaces/<str:slug>/budget-scenarios/<uuid:scenario_id>/variables/<uuid:assignment_id>/",
        BudgetScenarioVariableDetailEndpoint.as_view(),
        name="budget-scenario-variable-detail",
    ),
    path(
        "workspaces/<str:slug>/financial-variables/",
        FinancialVariableEndpoint.as_view(),
        name="financial-variables",
    ),
    path(
        "workspaces/<str:slug>/financial-variables/<uuid:variable_id>/",
        FinancialVariableDetailEndpoint.as_view(),
        name="financial-variable-detail",
    ),
    path(
        "workspaces/<str:slug>/expense-categories/",
        ExpenseCategoryEndpoint.as_view(),
        name="expense-categories",
    ),
    path(
        "workspaces/<str:slug>/expense-categories/<uuid:category_id>/",
        ExpenseCategoryDetailEndpoint.as_view(),
        name="expense-category-detail",
    ),
    path(
        "workspaces/<str:slug>/budgets/",
        BudgetEndpoint.as_view(),
        name="budgets",
    ),
    # Budgeted vs spent per category — the whole point of the module. Declared
    # before the <uuid> route so the literal never competes with it.
    path(
        "workspaces/<str:slug>/budgets/summary/",
        BudgetSummaryEndpoint.as_view(),
        name="budget-summary",
    ),
    path(
        "workspaces/<str:slug>/budgets/<uuid:budget_id>/",
        BudgetDetailEndpoint.as_view(),
        name="budget-detail",
    ),
    path(
        "workspaces/<str:slug>/expenses/",
        ExpenseEndpoint.as_view(),
        name="expenses",
    ),
    path(
        "workspaces/<str:slug>/expenses/<uuid:expense_id>/",
        ExpenseDetailEndpoint.as_view(),
        name="expense-detail",
    ),
    # Supporting documents (invoices, receipts) — the bytes live in the library
    path(
        "workspaces/<str:slug>/expenses/<uuid:expense_id>/documents/",
        ExpenseDocumentEndpoint.as_view(),
        name="expense-documents",
    ),
    path(
        "workspaces/<str:slug>/expenses/<uuid:expense_id>/documents/<uuid:asset_id>/",
        ExpenseDocumentEndpoint.as_view(),
        name="expense-document-detail",
    ),
    path(
        "workspaces/<str:slug>/expenses/<uuid:expense_id>/documents/<uuid:asset_id>/view/",
        ExpenseDocumentViewEndpoint.as_view(),
        name="expense-document-view",
    ),
]
