# Generated by Django 4.2.30 on 2026-07-14 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0132_merge_0129_and_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetScenario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_scenarios', to='db.workspace')),
            ],
            options={
                'db_table': 'budget_scenarios',
                'ordering': ('-fiscal_year', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FinancialVariable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], default='EXPENSE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('recurrence', models.CharField(choices=[('ONE_TIME', 'One time'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_variables', to='db.office')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_variables', to='db.workspace')),
            ],
            options={
                'db_table': 'financial_variables',
                'ordering': ('office__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BudgetScenarioVariable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='db.budgetscenario')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_scenarios', to='db.financialvariable')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_variables', to='db.workspace')),
            ],
            options={
                'db_table': 'budget_scenario_variables',
                'ordering': ('variable__name',),
            },
        ),
        migrations.CreateModel(
            name='BudgetScenarioEmployee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_scenarios', to='db.employee')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_scenarios', to='db.salary')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='db.budgetscenario')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_employees', to='db.workspace')),
            ],
            options={
                'db_table': 'budget_scenario_employees',
                'ordering': ('employee__full_name',),
            },
        ),
        migrations.CreateModel(
            name='BudgetBonus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed amount'), ('PERCENTAGE', 'Salary percentage')], default='FIXED', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('periodicity', models.CharField(choices=[('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('scenario_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='db.budgetscenarioemployee')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_bonuses', to='db.workspace')),
            ],
            options={
                'db_table': 'budget_bonuses',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='financialvariable',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'office', 'name'), name='unique_financial_variable_entity_name'),
        ),
        migrations.AddConstraint(
            model_name='financialvariable',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='financial_variable_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='financialvariable',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='financial_variable_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='budgetscenariovariable',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('scenario', 'variable'), name='unique_variable_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='budgetscenarioemployee',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('scenario', 'employee', 'salary'), name='unique_scenario_employee_salary'),
        ),
        migrations.AddConstraint(
            model_name='budgetscenarioemployee',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='scenario_employee_period_valid'),
        ),
        migrations.AddIndex(
            model_name='budgetscenario',
            index=models.Index(fields=['workspace', 'fiscal_year'], name='scenario_ws_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetscenario',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name', 'fiscal_year'), name='unique_budget_scenario_name_year'),
        ),
        migrations.AddConstraint(
            model_name='budgetscenario',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gte', models.F('period_start'))), name='budget_scenario_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='budgetbonus',
            constraint=models.CheckConstraint(check=models.Q(('value__gte', 0)), name='budget_bonus_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='budgetbonus',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='budget_bonus_period_valid'),
        ),
    ]
