# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0133_budgetscenario_financialvariable_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetCellOverride",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("row_key", models.CharField(max_length=255)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("scenario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cell_overrides", to="db.budgetscenario")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="budget_cell_overrides", to="db.workspace")),
            ],
            options={
                "db_table": "budget_cell_overrides",
                "ordering": ("row_key", "year", "month"),
                "indexes": [models.Index(fields=["scenario", "year", "month"], name="budget_override_period_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="budgetcelloverride",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("scenario", "row_key", "year", "month"), name="unique_budget_cell_override"),
        ),
        migrations.AddConstraint(
            model_name="budgetcelloverride",
            constraint=models.CheckConstraint(check=models.Q(("month__gte", 1), ("month__lte", 12)), name="budget_override_valid_month"),
        ),
        migrations.AddConstraint(
            model_name="budgetcelloverride",
            constraint=models.CheckConstraint(check=models.Q(("amount__gte", 0)), name="budget_override_amount_positive"),
        ),
    ]
