# Generated by Django 5.2.8 on 2026-07-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0135_musiccompany_musicgenre_musicparty_musicrelease_and_more")]

    operations = [
        migrations.AddField(
            model_name="musictrack",
            name="parent_track",
            field=models.ForeignKey(
                blank=True,
                help_text="Audio recording this video belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="db.musictrack",
            ),
        ),
        migrations.AddIndex(
            model_name="musictrack",
            index=models.Index(fields=["workspace", "parent_track", "kind"], name="music_video_parent_idx"),
        ),
    ]
