# Generated by Django 4.2.30 on 2026-09-09 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0142_contractchatmessage_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseImport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('stage', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('attempt', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'db_table': 'expense_imports',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='concept',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence',
            field=models.CharField(choices=[('ONE_TIME', 'One time'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='ONE_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='db.expense'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('series', 'expense_date'), name='unique_expense_occurrence'),
        ),
        migrations.AddField(
            model_name='expenseimport',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.fileasset'),
        ),
        migrations.AddField(
            model_name='expenseimport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='expenseimport',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.expense'),
        ),
        migrations.AddField(
            model_name='expenseimport',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='expenseimport',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='expenseimport',
            constraint=models.UniqueConstraint(fields=('workspace', 'asset'), name='unique_expense_import_asset'),
        ),
    ]
