# Generated by Django 4.2.30 on 2026-09-10 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0143_expense_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_expenses', to='db.budgetscenario'),
        ),
        migrations.AddField(
            model_name='expenseimport',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.budgetscenario'),
        ),
        migrations.CreateModel(
            name='FinanceComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('row_key', models.CharField(blank=True, max_length=255)),
                ('cell', models.CharField(blank=True, max_length=50)),
                ('comment_html', models.TextField()),
                ('reactions', models.JSONField(blank=True, default=list)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.expense')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='db.financecomment')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.budgetscenario')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'db_table': 'finance_comments',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BudgetRow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('row_key', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('documents', models.ManyToManyField(blank=True, to='db.fileasset')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.budgetscenario')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'db_table': 'budget_rows',
            },
        ),
        migrations.AddConstraint(
            model_name='financecomment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('expense__isnull', True), ('scenario__isnull', False)), models.Q(('expense__isnull', False), ('scenario__isnull', True)), _connector='OR'), name='finance_comment_one_target'),
        ),
        migrations.AddConstraint(
            model_name='budgetrow',
            constraint=models.UniqueConstraint(fields=('scenario', 'row_key'), name='unique_budget_row'),
        ),
    ]
